### ISSUE TITLE
标签误拦截了 siyuan:// 协议，导致无法在思源内正常使用块链接

### ISSUE THREAD

**Issue by frostime** [leolee9086/browserTab#1]
![image](https://github.com/leolee9086/browserTab/assets/27268127/f49d7078-c2fd-489c-ac83-51f5a56a70a9)

**Comment by cly2625** [comment]
+1 正常的页面跳转无法完成了

**Comment by leolee9086** [comment]
非常抱歉，因为之前的协议过滤做得太草率了所以造成了这个问题，之后会对协议作出必要的过滤

**Comment by leolee9086** [comment]
@frostime @cly2625 新版0.0.2应该已经解决了这个问题

**Comment by leolee9086** [comment]
我先关闭了，如果没有解决再重开这个issue
