### ISSUE TITLE
支持使用ctrl+click在默认浏览器中打开

### ISSUE THREAD

**Issue by HowcanoeWang** [leolee9086/browserTab#6]
目前还需要右键链接，打开->使用默认程序打开，需要一个快捷键来实现

**Comment by leolee9086** [comment]
![image](https://github.com/leolee9086/browserTab/assets/19915077/f6ee853b-78c7-4a1f-9976-73a9ece058de)
今天有点不太舒服，先加上这个开关。

**Comment by leolee9086** [comment]
打开之后点击直接用插件页签打开  ctrl+点击用外部浏览器打开  关闭之后相反
